timezone: Pacific Standard Time (PST)
tabs:
- title: ""
  contents:
    - time: Feb. 20, 2025
      title: Seattle application deadline
      description: null
    - time: Mar. 3, 2025
      title: Seattle acceptance notification
      description: null
    - time: Mar. 21, 2025
      title: New Orleans application deadline
      description: null
    - time: Apr. 7, 2025
      title: New Orleans acceptance notification
      description: null